# Site settings
title: Mitch Anderson
email: iammitch@iammitch.com
description: > # this means to ignore newlines until "baseurl:"
  These days it's not too easy for an adult to further their education. Beyond
  that of "professional" degree programs, there just aren't a whole lot of reasonable
  options for the curious common-man of "post-collegiate age." While it's a shame,
  I'd hate for it to be so much a hinderance as to blind me completely of everything
  around us. To create, one must know and to know one must learn.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tmanderson.github.io" # the base hostname & protocol for your site
twitter_username: tmanderson
github_username:  tmanderson

# Build settings
markdown: kramdown
